name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 20.x
          cache: "pnpm"

      - run: bun install --force
      - run: bun run ci
